[package]
name = "spreadsheet"
version = "0.1.0"
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grpcio = {  version = "0.8.0", default-features = false }


[build-dependencies]
protoc-grpcio = "1.0.2"
