version: "3"
services:
    spreadsheet:
        image: "public.ecr.aws/d2r0d0k3/spreadsheet:latest"
        stdin_open: true
        ports:
            - "9090:9090"
    envoy:
        image: "envoy-local"
        ports:
            - "8080:8080"
            - "9901:9901"
        command:
            - "--config-path /etc/envoy/envoy.yaml"
            - "--mode serve"
            - "--concurrency 1"
