version: "3"
services:
    spreadsheet:
        image: "public.ecr.aws/d2r0d0k3/spreadsheet:latest"
        stdin_open: true
        ports:
            - "9090:9090"
    envoy:
        image: "envoyproxy/envoy:v1.17.1"
        volumes:
            - ./envoy.yaml:/etc/envoy/envoy.yaml
        ports:
            - "8080:8080"
            - "9901:9901"
